<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_check</name>
   <tag></tag>
   <elementGuidId>4f446cac-8d4a-4cd7-8ba9-297c9d8008b9</elementGuidId>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;accordiongroup-571-1203-panel&quot;)/div[@class=&quot;panel-body&quot;]/div[@class=&quot;form-group form-md-line-input ng-scope&quot;]/div[@class=&quot;col-md-6&quot;]/div[@class=&quot;md-radio-inline&quot;]/div[@class=&quot;md-radio&quot;]/label[1]/span[@class=&quot;check&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>check</value>
   </webElementProperties>
</WebElementEntity>
